"""post-markdown

Revision ID: a018052e4bd9
Revises: 660ebcd1bcea
Create Date: 2017-08-13 06:14:23.700752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a018052e4bd9'
down_revision = '660ebcd1bcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    op.create_table('userstemp',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('password_hash', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('confirmed', sa.NUMERIC(), nullable=True),
    sa.Column('about_me', sa.TEXT(), nullable=True),
    sa.Column('last_seen', sa.NUMERIC(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('member_since', sa.NUMERIC(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('avatar_hash', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
