"""comment delete

Revision ID: eb2b1073e853
Revises: 8780bcb67912
Create Date: 2017-10-01 13:41:33.263784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2b1073e853'
down_revision = '8780bcb67912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'deleted')
    # ### end Alembic commands ###
